sudo: required
services:
  - docker

before_install:
  - docker build -t rorlikow/ng-base -f Dockerfile.dev .


script:
  - docker run -e CI=true rorlikow/ng-base npm run test -- --no-watch --no-progress
