name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t rorlikow/ng-base -f Dockerfile.dev .

      - name: Run Tests
        run: docker run -e CI=true rorlikow/ng-base npm run test-headless

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          version_label: "1"
          region: us-east-1


