name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t rorlikow/ng-base -f Dockerfile.dev .

      - name: Run Tests
        run: docker run -e CI=true rorlikow/ng-base npm run test-headless

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-us-east-1-295482541427
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip


